### ISSUE TITLE
post code into next cell

### ISSUE THREAD

**Issue by tischi** [haesleinhuepf/bia-tischi#11]
it would be interesting to see whether one could manufacture that the suggested code is put into the next cell, without being yet executed.

**Comment by tischi** [comment]
`cbob`  does the job. I think this is quite awesome now:

<img width="1189" alt="image" src="https://github.com/haesleinhuepf/bia-tischi/assets/2157566/445c1118-c1d4-4903-96e7-d9da48b71805">

I would actually remove all the other bobs and just keep cbob, and rename it to bob.

What do you think @haesleinhuepf ?

**Comment by haesleinhuepf** [comment]
This is amazing @tischi ! I love it
