### ISSUE TITLE
bot names and model choosing

### ISSUE THREAD

**Issue by tischi** [haesleinhuepf/bia-tischi#17]
I think we should use some gender free name.

What about simply: `%gpt_4_0` and `%gpt_3_5`? Like this the user could also switch models on the fly, e.g. using the more expensive `4.0` only the difficult tasks or when the answer of `3.5` is not satisfactory.

**Comment by haesleinhuepf** [comment]
> I think we should use some gender free name.

That's a very good point! It should also fulfill these criteria: IMO:
* Short (max 3 characters) 
* easy to type. e.g. not containing _

**Comment by haesleinhuepf** [comment]
I asked chatGPT4 "list ten short firstnames (<= 3 characters) which could be used for males and females" and it responded:

```
Certainly! Here are ten short, unisex first names that are three characters or less:

Sam
Lee
Pat
Max
Kim
Jay
Alex (though often a short form for longer names like Alexander or Alexandra)
Jo
Sky
```

**Comment by haesleinhuepf** [comment]
As just discussed: We keep it as `bob` and bring back the voice (as optional dependency) which is female.
