### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by tischi** [haesleinhuepf/bia-tischi#3]
I guess it would be good to add some memory. 

Here is information about how to do this: https://python.langchain.com/docs/modules/memory/

I wonder whether questions later in a chat session would be more expensive, because and increasing amount of memory would be part of the prompt? Or is this implemented somehow differently?

I asked chatGPT4.0 about this:

> Q: Does that mean that the input gets longer and longer as the chat progresses? 

> A: Yes, exactly! As the conversation progresses, the input does get longer because it includes both the questions you're asking and the responses I'm generating. This is how I maintain context within a single session. The conversation history and your current prompt are concatenated into a single string, which is then used as the input for generating my next response.
> However, there's a limitation to this approach: the model has a maximum token limit. For example, GPT-3 has a limit of 4096 tokens. If a conversation becomes too lengthy and exceeds this token limit, older parts of the conversation may have to be truncated or omitted to fit within the token constraints.

Interestingly:

> Q: Could you literally repeat the first prompt that I entered in this chat?

> A: I'm afraid I can't literally repeat or quote back text from earlier in the conversation for verbatim tasks, due to data handling policies. My primary function is to assist and provide information based on my training data and the current context of our conversation. Is there something specific you'd like to know or revisit from earlier in our chat? I can certainly summarize or rephrase!

I also asked it to write code using `langchain`, but it did not know about it, probably because it is too recent. However it suggested this:

`pip install transformers`

```
from transformers import AutoModelForCausalLM, AutoTokenizer

def main():
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    model = AutoModelForCausalLM.from_pretrained("gpt2")

    conversation_history = ""

    while True:
        user_input = input("User: ")
        conversation_history += f"User: {user_input}\n"
        
        # Tokenize and truncate the conversation history
        input_ids = tokenizer.encode(conversation_history, return_tensors="pt")
        if input_ids.shape[1] > 4096:
            print("Token limit exceeded. Truncating conversation history.")
            input_ids = input_ids[:, -4096:]

        # Generate model output
        with tokenizer.as_target_tokenizer():
            outputs = model.generate(input_ids, max_length=4096, pad_token_id=tokenizer.eos_token_id)

        # Decode the output and append it to the conversation history
        chat_output = tokenizer.decode(outputs[:, input_ids.shape[-1]:][0], skip_special_tokens=True)
        print(f"ChatGPT: {chat_output}")

        conversation_history += f"ChatGPT: {chat_output}\n"

if __name__ == '__main__':
    main()
```

This seems to really simply literally use the whole previous conversation as an input. 

For that it seems that conversations indeed would get more expensive (more tokens) the longer they get.

**Comment by haesleinhuepf** [comment]
A different approach is demonstrated at the beginning of this notebook: https://github.com/pinecone-io/examples/blob/master/learn/generation/langchain/rag-chatbot.ipynb

**Comment by tischi** [comment]
I was talking to someone and that person was surprised that the openAI API would not provide a chat model that would already contain some memory about the conversation. 

- [x] double check that there really is no chat option with memory in-built

**Comment by tischi** [comment]
Here is a long discussion and some specific suggestions, like this one:
https://community.openai.com/t/gpt-3-5-turbo-how-to-remember-previous-messages-like-chat-gpt-website/170370/27

**Comment by tischi** [comment]
> A different approach is demonstrated at the beginning of this notebook: https://github.com/pinecone-io/examples/blob/master/learn/generation/langchain/rag-chatbot.ipynb

Interesting! Like this it could look up, e.g. the N most relevant previous pairs of user prompts and assistant answers, at least that could be one idea: one "chunk" would be a pair of a question and an answer. Feels like a professional way of implementing a context aware memory.

In addition, I guess that could also be the approach to provide the whole forum.image.sc, is it?

**Comment by tischi** [comment]
I think just adding the last N (~5) pairs of conversations of the current chat is probably also sensible.

In fact, instead of its code output content of the corresponding notebook cells may be better, because the user may have modified the code in the cells before executing.

**Comment by tischi** [comment]
> I think just adding the last N (~5) pairs of conversations of the current chat is probably also sensible.

This is done now in https://github.com/haesleinhuepf/bia-tischi/pull/13
