### ISSUE TITLE
option for only showing the code

### ISSUE THREAD

**Issue by tischi** [haesleinhuepf/bia-tischi#7]
I think in terms of safety and responsibilities I would prefer to also have an option where it only shows the code and then it is the responsibility of the user to copy and paste (parts of) the code into the executable cell.

Is that technically possible?

If you agree, but if you want to keep the option to directly execute, could we have different jupyter magick for this?

For example:

%bia-tischi would not execute the code, but %bia-bunny would?

**Comment by haesleinhuepf** [comment]
> could we have different jupyter magick for this?
> 
> For example:
> 
> %bia-tischi would not execute the code, but %bia-bunny would?

Yes, that makes a lot of sense! One would need to refactor this function:
https://github.com/haesleinhuepf/bia-tischi/blob/1354c4def483803e12f2d537dc8237eb1aea4606/src/bia_tischi/_machinery.py#L10C3-L30C3

**Comment by tischi** [comment]
Does that mean you would be happy for it to _always_ only show the code or do you want to have the _flexibility_ for it to execute or not?

**Comment by haesleinhuepf** [comment]
I'd say having two %magic commands is great: one for generating code only and one for generating+ executing

**Comment by tischi** [comment]
OK, I will work on this in the coming days.
